### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by nilskp** [melix/jmh-gradle-plugin#29]
The reason for #28 was that I was using Scala to write the benchmark. It would be nice to have support for the other JVM languages, just like JMH itself.

**Comment by superbobry** [comment]
I'm using Scala with `jmh-gradle-plugin` as well. The `BenchmarkList` gets generated, but there's no benchmarks in it. Possibly a classpath issue?

**Comment by nilskp** [comment]
@superbobry I have yet to see that list actually populated, even with working benchmarks, so I think that's a red herring.

My current approach is to make a Java sandwich with Scala inside, i.e. a Java class to define all setup and public fields, with @Setup and @Param annotation. I then extend that with a Scala class that has all the real benchmarking, and finish that off my extending the Scala class with a Java class, no content. This works, but is obviously annoying.

**Comment by superbobry** [comment]
If I understand correctly, `jmh-gradle-plugin` relies on `jmh-generator-annprocess` for generating benchmarks. This generator operates on the source-level, so obviously it doesn't work for non-Java sources. 

JMH comes with another generator which generates benchmarks from bytecode (used by Maven [archetype](http://hg.openjdk.java.net/code-tools/jmh/file/bdfc7d3a6ebf/jmh-archetypes/jmh-scala-benchmark-archetype/src/main/resources/archetype-resources/pom.xml) for Scala). So I guess a proper way to handle the issue is to change `jmh-gradle-plugin` to use a bytecode-level generator.
