### ISSUE TITLE
Benchmarks that rely on ServiceLoader do not work.

### ISSUE THREAD

**Issue by ewaryst1** [melix/jmh-gradle-plugin#42]
I want to write a Benchmark which uses another project that uses the ServiceLoader which in order to work requires a file in the classpath at the location META-INF/services/some.interface.name.
The problem is now that this plugin does not include the META-INF/services content into the benchmark-jar, see the JMHPlugin.groovy commit in changeset fc24778:
```
from(project.configurations.jmh.collect { it.isDirectory() ? it : project.zipTree(it) }) {
                    exclude '**/META-INF/services/**'
                }
```

What is the reason to exclude this content and is there a workaround to benchmark ServiceLoader based code?

Help is appreciated.

**Comment by vyazelenko** [comment]
This logic only applies in *simple mode*, i.e. when fat jar is created manually. The content of ```META-INF/services``` is excluded, because if multiple source jars have those defined generated fat jar will be broken.

However it is possible to use [shadow](https://github.com/johnrengelman/shadow) plugin to build jar with benchmarks. To do this simply apply [shadow](https://github.com/johnrengelman/shadow) plugin in your build:
```groovy
plugins {
    id 'java'
    id 'me.champeau.gradle.jmh' version '0.2.0'
    id 'com.github.johnrengelman.shadow' version '1.2.2'
}
```
Once you do this you'll be able to use full power of [shadow](https://github.com/johnrengelman/shadow) directly from ```jmhJar``` block:
```groovy
jmhJar {
    mergeServiceFiles()
}
```
For more informarion have a look in the documentation for [shadow](https://github.com/johnrengelman/shadow) plugin.

**Comment by ewaryst1** [comment]
Thanks vyazelenko, your suggested solution works for me.
